title: DIACR-Ita
description: Diachronic lexical semantics in Italian
logo: img/logo2.png
show_downloads: false
baseurl: ""
url: "https://diacr-ita.github.io"
google_analytics: UA-166280698-1
theme: jekyll-theme-dinky
gems:
  - jekyll-redirect-from
